name: Follow Back GitHub Followers

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'

  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub UI

jobs:
  follow-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${{ runner.home }}/.local/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: poetry install

      - name: Run follow_back script
        run: poetry run python follow_back/follow.py ${{ github.repository_owner }} 300
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
